<?php echo $this->doctype(); ?>
 
<html lang="pt-BR">
    <head>
        <meta charset="utf-8" />
        <?php echo $this->headTitle('Agenda de Contatos'); ?>
 
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
 
        <!-- Styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');
        ?>
 
        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js');
        ?>
    </head>
    <body>
        <div id="wrap">
            <div class="container">
                <div class="page-header">
                    <h1>Agenda de Contatos</h1>
                </div>
                <div class="content">
                    <?php echo $this->content; ?>
                </div>
            </div>
        </div>
        <div id="footer">
            <div class="container">
                <p class="muted credit pull-left">Company <a href="">© 2013</a></p>
                <p class="muted credit pull-right">Desenvolvido por <a href="http://igorrocha.com.br">Igor Rocha</a>.</p>
            </div>
        </div>
 
        <?php echo $this->inlineScript(); ?>
    </body>
</html>